export const playlist =
  [{ url: 'https://radio.robingiel.com/magic',
     title: 'Magic 96.5 FM',
     isUnboundedStream : true},
     {url:  'https://radio.robingiel.com/massive',
     title: 'Massive 103.5 FM',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/power',
     title: 'Power FM Aruba',
     isUnboundedStream: true},
     { url: 'https://radio.robingiel.com/top',
     title: 'Top FM 95',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/cool',
     title: 'Cool FM Aruba',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/heartradio',
     title: 'Heart Music Radio 106.7 FM',
     isUnboundedStream : true},
     { url: 'https://securestreams5.autopo.st:1922/;stream.nsv&error=ok',
     title: '99.9 FM Galactica',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/hit94',
     title: 'Hit 94 FM',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/canal90',
     title: 'Canal 90 FM' ,
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/boguia',
     title: 'Bo GUIA FM' ,
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/mega88',
     title: 'Mega 88 FM Aruba',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/bluefm',
     title: 'Blue FM 107.5',
     isUnboundedStream : true},
     { url: 'https://ice1.securenetsystems.net/DEMOSTN?playSessionID=6AEB38B7-CA0F-2F2B-384DB852DD5B857C',
     title: 'AFM Aruba' ,
     isUnboundedStream : true},
     { url: 'https://streamer.radio.co/s579e30929/listen',
     title: 'Super Exitos Aruba',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/fresh',
     title: 'Fresh FM Aruba',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/easy',
     title: 'Easy FM Aruba',
     isUnboundedStream : true},
     { url: 'https://radio.robingiel.com/vip',
     title: 'VIP Radio Aruba',
     isUnboundedStream : true}
     ];